language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dontyouknowashutosh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dontyouknowashutosh/docker-react npm run test